Use a user agent library
callumrollo/erddaplogs pull request #17
Opened 2024-05-21 20:25 UTC by ChrisJohnNOAA

to detect bots
and to help with parsing/anonymization of user agent strings

2024-05-21 20:49 UTC, callumrollo requested changes
Looks good! I've tested it locally too. I've made a couple of small review requests

2024-05-21 20:49 UTC, callumrollo commented on logparse.py
>          """Filter out requests from bots."""
remove the kwarg `bots=None` as no longer used

2024-05-21 20:49 UTC, callumrollo commented on logparse.py
> +from user_agents import parse
add user_agents to env.yml pip section

2024-05-21 21:04 UTC, ChrisJohnNOAA commented
> Looks good! I've tested it locally too. I've made a couple of small review requests

Done

2024-05-22 07:11 UTC, callumrollo approved these changes

2024-05-22 07:12 UTC, merged